version: '3.8'

services:
  web:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "BookingApplicationDB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "martin123"
    expose:
      - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
volumes:
  db-data:
