apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: kiii-proekt
spec:
  replicas: 5
  selector:
    matchLabels:
      name: booking
  template:
    metadata:
      labels:
        name: booking
    spec:
      containers:
        - name: booking-container
          image: martin0411/bookingapplication:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: config
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kiii-secret
                  key: password
          volumeMounts:
          - name: keys
            mountPath: /keys
      volumes:
      - name: keys
        persistentVolumeClaim:
          claimName: keys-pvc
