kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc
  namespace: kiii-proekt
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
