apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
  namespace: kiii-proekt
spec:
  serviceName: db
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        namespace: kiii-proekt
    spec:
      containers:
        - name: postgres-container
          image: postgres:latest
          envFrom:
            - configMapRef:
                name: config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kiii-secret
                  key: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: pvc
